#!/usr/bin/env python3
"""
Rebuild js/components.js for each design concept.

Why: the header/footer live in site-header.dc.html / site-footer.dc.html.
Browsers block fetching those files when a page is opened by double-click
(file://) or from some hosts, so the header disappears. components.js embeds
them (plus local React) so every page renders its header/footer anywhere.

Run this after editing any *.dc.html file:   python3 build.py
"""
import json, pathlib

ROOT = pathlib.Path(__file__).parent
REACT = {
    "https://unpkg.com/react@18.3.1/umd/react.production.min.js": "js/vendor/react.production.min.js",
    "https://unpkg.com/react-dom@18.3.1/umd/react-dom.production.min.js": "js/vendor/react-dom.production.min.js",
}

for concept in ["editorial", "modern", "quiet"]:
    d = ROOT / concept
    parts = [
        "/* AUTO-GENERATED by build.py — do not edit. Edit the *.dc.html files, then run: python3 build.py */",
        "(function () {",
        "  var R = window.__resources = window.__resources || {};",
    ]
    parts += [f"  R[{json.dumps(k)}] = {json.dumps(v)};" for k, v in REACT.items()]
    parts.append("  var B = window.__resourceBlobs = window.__resourceBlobs || {};")
    for f in sorted(d.glob("*.dc.html")):
        parts.append(f"  B[{json.dumps('./' + f.name)}] = new Blob([{json.dumps(f.read_text())}], {{ type: 'text/html' }});")
    parts.append("})();\n")
    (d / "js" / "components.js").write_text("\n".join(parts))
    print(f"{concept}/js/components.js  <-", ", ".join(p.name for p in sorted(d.glob('*.dc.html'))))
